# Generated by Django 4.0.3 on 2022-03-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsapp',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
