# Generated by Django 4.0.3 on 2022-03-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contactsapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsapp',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactsapp',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactsapp',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
