# Generated by Django 4.0.3 on 2022-03-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactsapp_email_alter_contactsapp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsapp',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
